services:
  db:
    image: postgres:17
    container_name: gestor-nutricional-db
    environment:
      POSTGRES_DB: gestor_nutricional
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: gestor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
