[project]
name = "gestor-nutricional"
version = "0.1.0"
description = "Gestor nutricional inteligente"
requires-python = ">=3.14"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy",
    "psycopg[binary]",
    "httpx",
]

[dependency-groups]
dev = [
    "alembic>=1.19.1",
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
