"""add status to meal suggestions

Revision ID: 50e6c189eab5
Revises: 58eb5b87878d
Create Date: 2026-09-01 07:42:13.767240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e6c189eab5'
down_revision: Union[str, Sequence[str], None] = '58eb5b87878d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_suggestions', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_suggestions', 'status')
    # ### end Alembic commands ###
