"""add unique constraint to meal suggestions

Revision ID: 58eb5b87878d
Revises: 8a263db703a5
Create Date: 2026-08-31 17:00:26.247896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58eb5b87878d'
down_revision: Union[str, Sequence[str], None] = '8a263db703a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_meal_suggestion_slot_meal', 'meal_suggestions', ['meal_slot_id', 'prepared_meal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_meal_suggestion_slot_meal', 'meal_suggestions', type_='unique')
    # ### end Alembic commands ###
