"""add status to meal plans

Revision ID: 7317d92826ad
Revises: 859f956ea37d
Create Date: 2026-09-01 21:47:36.756754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7317d92826ad'
down_revision: Union[str, Sequence[str], None] = '859f956ea37d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "meal_plans",
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="draft",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'status')
    # ### end Alembic commands ###
