"""add generation to meal suggestions

Revision ID: 859f956ea37d
Revises: 50e6c189eab5
Create Date: 2026-09-01 15:05:11.321281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859f956ea37d'
down_revision: Union[str, Sequence[str], None] = '50e6c189eab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_suggestions', sa.Column('generation', sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_suggestions', 'generation')
    # ### end Alembic commands ###
