"""add meal suggestions

Revision ID: 8a263db703a5
Revises: ef6a4eddf9cf
Create Date: 2026-08-28 12:19:43.071460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a263db703a5'
down_revision: Union[str, Sequence[str], None] = 'ef6a4eddf9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_slot_id', sa.Integer(), nullable=False),
    sa.Column('prepared_meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_slot_id'], ['meal_slots.id'], ),
    sa.ForeignKeyConstraint(['prepared_meal_id'], ['prepared_meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_suggestions_id'), 'meal_suggestions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_suggestions_id'), table_name='meal_suggestions')
    op.drop_table('meal_suggestions')
    # ### end Alembic commands ###
